apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: enrich-authn-deployment-hpa
  namespace: iris
spec:
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
