apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrich-authn-deployment
  namespace: iris
spec:
  template:
    spec:
      containers:
        - name: enrich-authn-container
          resources:
            requests:
              cpu: "0.5"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "1024Mi"
